version: '3'

services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - USER_ID=${USER_ID}
          - GROUP_ID=${GROUP_ID}
    image: 'dockerfile-laravel'
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    command: [ "php-fpm" ]
    ports:
      - "8000:8000"

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: laravel-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  node:
    image: node:14
    container_name: laravel-node
    volumes:
        - .:/var/www
    working_dir: /var/www
    command: /bin/sh -c "while sleep 1000; do :; done"

  #Nginx Service
  webserver:
      image: nginx:alpine
      container_name: laravel-nginx
      restart: unless-stopped
      tty: true
      ports:
          - "8010:80"
      volumes:
          - .:/var/www
          - ./default.conf:/etc/nginx/conf.d/default.conf
      networks:
          - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
