version: '3'

services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'dockerfile-laravel'
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    command: [ "php-fpm" ]
    ports:
      - "8005:8005"

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: laravel-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3315:3315"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

# ... (інші конфігурації)

  node:
    image: node:14
    container_name: laravel-node
    volumes:
        - .:/var/www
    working_dir: /var/www
    command: /bin/sh -c "while sleep 1000; do :; done"

#Docker Networks
networks:
  app-network:
    driver: bridge
